# Build go-acme/lego

name: lego

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'go-acme/lego'
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)
        echo "Checking out latest tag $LATEST_TAG"
        git checkout $LATEST_TAG
        echo "Set CGO_ENABLED=1 to enabling dymanic linking"
        sed -i 's|^export.*CGO_ENABLED.*$|export CGO_ENABLED=1|g' Makefile
        make build
        ./dist/lego --version
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lego-build
        path: ./dist/lego
